name: .NET Core

on:
  push:
    branches:
      - use_composite_action

env:
  AZURE_WEBAPP_NAME: as-rvdg-vehicles-api    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5.0.301'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: cg-roelvandegrint/roel-composite@0.1.0
